[package]
name = "burn-rl"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rand = "0.8.5"
burn = { version = "0.10.0", features = ["ndarray", "autodiff"] }
gym-rs = { path = "../../gym-rs" }
ringbuffer = "0.15.0"
